CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `sex` VARCHAR(16),
  `number` VARCHAR(128) NOT NULL UNIQUE,
  `password` VARCHAR(128) NOT NULL,
  `Profession` VARCHAR(32) NOT NULL,
  `Department` VARCHAR(128),
  `Major` VARCHAR(128),
  `class` VARCHAR(128),
  `year` INT(16),
  `power` INT(8) NOT NULL,
  `lastlogin` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `title` (
  `id` INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `teacherid` int(64),
  `studentid` int(64) DEFAULT 0,
  `studentnum` VARCHAR(128) DEFAULT '',
  `studentname`VARCHAR(128) DEFAULT '',
  `type` int(8),
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
