CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL UNIQUE,
  `nickname` VARCHAR(128) NOT NULL,
  `avatar` VARCHAR(128),
  `password` VARCHAR(128),
  `isadmin` BOOLEAN NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastlogin` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isactive` BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (`id`, `name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;