CREATE TABLE IF NOT EXISTS `user` (
  `id` int(32) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(20) NULL,
  `unionid` varchar(128) UNIQUE NOT NULL,
  `isadmin` BOOLEAN DEFAULT FALSE,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS `ware` (
  `id` INT(64) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `desc` VARCHAR(100),
  `category` VARCHAR (50) NOT NULL,
  `inventory` INT(16),
  `status` INT(8) DEFAULT 1,
  `price` DOUBLE(10, 2) NOT NULL ,
  `saleprice` DOUBLE(10, 2),
  `avatar` VARCHAR(128),
  `image` VARCHAR(128),
  `detailpic` VARCHAR(128),
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


